### ISSUE TITLE
DB details?

### ISSUE THREAD

**Issue by anand-singh** [knoldus/jwt-akka-http-example#2]
- Update MySQL details in README

**OR**

- Connect with H2 DB

**Comment by satendrakumar06** [comment]
[MySQL](https://github.com/knoldus/jwt-akka-http-example/blob/master/src/main/scala/com/knoldus/api/handler/JwtApiHandler.scala) 
@knoldernarayan ^^^ Is this correct ?

**Comment by knoldernarayan** [comment]
@satendrakumar06  Yes it is Mysql
